Repository prgrms-web-devcourse-final-project/WEB2_3_DFBF_FE, pull requests merged in 2025-02, with the labels that each got.

#4 [chore] pwa 세팅
  dev-dist/sw.js
  dev-dist/workbox-54d0af47.js
  package-lock.json
  package.json
  public/icons/apple-touch-icon-114x114.png
  public/icons/apple-touch-icon-120x120.png
  public/icons/apple-touch-icon-144x144.png
  public/icons/apple-touch-icon-152x152.png
  public/icons/apple-touch-icon-57x57.png
  public/icons/apple-touch-icon-60x60.png
  public/icons/apple-touch-icon-72x72.png
  public/icons/apple-touch-icon-76x76.png
  src/main.tsx
  src/pages/home/Home.tsx
  src/vite-env.d.ts
  vite.config.ts
Labels: 👷chore

#2 [design] 헤더 컴포넌트 / 레이아웃 잡기
  src/App.tsx
  src/assets/icons/ellipsisButton.svg
  src/assets/icons/icons.svg
  src/assets/icons/logo.png
  src/assets/icons/notification.svg
  src/layouts/Header.tsx
  src/layouts/LandingLayout.tsx
  src/pages/home/Home.tsx
  src/pages/landing/Landing.tsx
Labels: 🎨design

#6 [feat] 상수 파일 추가
  src/constants/emotions.ts
  src/constants/index.ts
  src/constants/limits.ts
  src/constants/validation.ts
Labels: ✨feat

#10 [design]input 컴포넌트 퍼블리싱
  src/components/Input.tsx
Labels: 🎨design

#16 [design] 감정 뱃지 컴포넌트 구현
  dev-dist/sw.js
  src/components/EmotionBadge.tsx
  src/constants/emotions.ts
Labels: 🎨design

#18 [feat] 폰트 추가, 파비콘 변경
  index.html
  public/favicon.png
  public/vite.svg
  src/layouts/Header.tsx
  src/styles/fonts.css
  src/styles/index.css
  src/styles/tailwind.css
  src/styles/typography.css
Labels: 🎨design

#20 [design] 검색바 퍼블리싱
  src/assets/icons/search-icon/search-icon-default.svg
  src/assets/icons/search-icon/search-icon-hover.svg
  src/components/SearchBar.tsx
Labels: 🎨design

#24 [design] 감정기록카드 퍼블리싱
  src/components/EmotionRecordCard.tsx
Labels: 🎨design

#26 [feat] 버튼 컴포넌트 추가
  src/components/Button.tsx
Labels: ✨feat

#27 [feat] 하단 nav 추가
  index.html
  src/App.tsx
  src/assets/icons/nav/chat-active.svg
  src/assets/icons/nav/chat-default.svg
  src/assets/icons/nav/home-active.svg
  src/assets/icons/nav/home-default.svg
  src/assets/icons/nav/index.ts
  src/assets/icons/nav/mypage-active.svg
  src/assets/icons/nav/mypage-default.svg
  src/layouts/BottomNav.tsx
  src/layouts/LandingLayout.tsx
Labels: ✨feat

#33 [design]/더보기 셀렉트 박스 퍼블리싱
  src/components/MoreSelectBox.tsx
  src/layouts/Header.tsx
  src/styles/index.css
  src/styles/tailwind.css
Labels: 🎨design

#31 [design] 대화방 음악 재생 퍼블리싱
  src/assets/icons/pause.svg
  src/assets/icons/play.svg
  src/pages/chat/Chat.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  src/styles/tailwind.css
Labels: 🎨design

#32 [design]modal 컴포넌트 퍼블리싱
  src/App.tsx
  src/components/Modal.tsx
  src/store/modalStore.ts
Labels: 🎨design

#36 [feat] 더보기 셀렉트 박스 컴포넌트화
  src/App.tsx
  src/assets/icons/ellipsis-icon.svg
  src/assets/icons/notification.svg
  src/components/MoreOptionsSelect.tsx
  src/components/MoreSelectBox.tsx
  src/layouts/Header.tsx
  src/layouts/LandingLayout.tsx
  src/layouts/Layout.tsx
Labels: ✨feat

#34 [design] 카드 상세 모달 퍼블리싱
  src/assets/icons/comment-icon-white.svg
  src/assets/icons/headset-icon.svg
  src/assets/icons/home-icon.svg
  src/components/CardDetailModal.tsx
  src/components/ChatActionButtons.tsx
  src/components/Overlay.tsx
Labels: 🎨design

#38 [feat] 레이아웃 css 수정, MusicCard 컴포넌트 추가
  dev-dist/sw.js
  index.html
  src/assets/icons/pause-circle.svg
  src/assets/icons/play-circle.svg
  src/assets/images/default.png
  src/components/Button.tsx
  src/components/MusicCard.tsx
  src/layouts/BottomNav.tsx
  src/layouts/Layout.tsx
Labels: ✨feat, 🎨design

#47 [feat] 헤더 레이아웃 수정, 메인카드 컴포넌트
  src/assets/icons/logo.png
  src/components/Button.tsx
  src/components/MainCard.tsx
  src/layouts/Layout.tsx
  src/layouts/header/Header.tsx
  src/layouts/header/HedaerLayout.tsx
Labels: ✨feat, 🎨design

#48 [design] 채팅방 연결 로딩시트 퍼블리싱
  src/App.tsx
  src/assets/icons/logo.svg
  src/assets/icons/sad-icon.svg
  src/components/ChatConnectLoadingSheet.tsx
  src/components/MusicAnimation.tsx
  src/pages/landing/Landing.tsx
Labels: 🎨design

#46 [design] 모달 시트 레이아웃 & 상세 모달 시트 퍼블리싱
  src/App.tsx
  src/assets/icons/close-icon.svg
  src/assets/icons/comment-icon-white.svg
  src/assets/icons/comment-icon.svg
  src/assets/icons/headset-icon-gray.svg
  src/assets/icons/home-icon.svg
  src/components/CardDetailButtons.tsx
  src/components/CardDetailModal.tsx
  src/components/ChatActionButtons.tsx
  src/layouts/ModalSheetLayout.tsx
Labels: 🎨design

#53 [design]지난 대화 기록 퍼블리싱
  src/App.tsx
  src/components/ChatHistoryCard.tsx
  src/components/ChatRecordCard.tsx
  src/layouts/header/HedaerLayout.tsx
  src/pages/chat/Chat.tsx
  src/types/chat.d.ts
  src/types/post.d.ts
Labels: 🎨design

#54 [feat] 인풋버튼 컴포넌트, Input 컴포넌트 수정
  src/components/ButtonInput.tsx
  src/components/Input.tsx
  src/styles/tailwind.css
Labels: ✨feat, 🎨design

#55 [design] 음악 검색 시트 퍼블리싱
  src/components/InfoMessage.tsx
  src/components/MusicSearchList.tsx
  src/components/MusicSearchSheet.tsx
  src/components/SearchBar.tsx
  src/layouts/ModalSheetLayout.tsx
Labels: 🎨design

#60 [design] 404 페이지 퍼블리싱
  src/App.tsx
  src/pages/NotFound.tsx
Labels: 🎨design

#63 [design] 헤더 글작성 버튼 추가
  src/assets/icons/post-icon.svg
  src/components/MoreOptionsSelect.tsx
  src/layouts/header/Header.tsx
Labels: 🎨design

#65 [chore] 컴포넌트 폴더 시트파일 분리
  src/components/modalSheet/CardDetailButtons.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/components/modalSheet/MusicSearchList.tsx
  src/components/modalSheet/MusicSearchSheet.tsx
Labels: 👷chore

#66 [design] 채팅 페이지 퍼블리싱
  index.html
  src/App.tsx
  src/assets/icons/send-icon.svg
  src/layouts/BottomNav.tsx
  src/layouts/Layout.tsx
  src/layouts/header/HeaderChat.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatRoom.tsx
  src/types/chat.d.ts
Labels: 🎨design

#69 [design] 메인페이지 퍼블리싱
  src/components/EmotionBadge.tsx
  src/constants/emotions.ts
  src/layouts/Layout.tsx
  src/pages/home/Home.tsx
Labels: 🎨design

#71 [design] 버튼 컴포넌트 속성 변경 & 인풋 / 버튼 인풋 merge
  src/components/Button.tsx
  src/components/ButtonInput.tsx
  src/components/ChatConnectLoadingSheet.tsx
  src/components/ChatHistoryCard.tsx
  src/components/Input.tsx
  src/components/InputField.tsx
  src/components/Modal.tsx
  src/components/MusicCard.tsx
  src/pages/NotFound.tsx
  src/pages/landing/Landing.tsx
Labels: 🎨design

#72 [design] 회원가입 페이지 퍼블리싱
  src/App.tsx
  src/components/InputField.tsx
  src/layouts/Layout.tsx
  src/pages/signup/SignUp.tsx
Labels: 🎨design

#75 [design] 감정 상세 모달 재생 버튼 추가
  src/assets/icons/pause-icon-gray.svg
  src/assets/icons/play/play-circle.svg
  src/assets/icons/play/play-icon-gray.svg
  src/assets/icons/play/play.svg
  src/components/MusicCard.tsx
  src/components/modalSheet/CardDetailButtons.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
Labels: 🎨design

#76 [feat] 채팅방 음악 플레이어 기능 구현
  .gitignore
  package-lock.json
  package.json
  src/apis/youtube.ts
  src/assets/icons/play-icon-gray.svg
  src/components/YouTubeAudioPlayer.tsx
  src/main.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  vite.config.ts
Labels: ✨feat

#78 [design] 로그인 페이지
  src/App.tsx
  src/assets/icons/kakao-icon.svg
  src/assets/icons/logo.png
  src/assets/icons/logo.svg
  src/layouts/header/Header.tsx
  src/pages/Login.tsx
Labels: 🎨design

#80 [feat] 카드 상세 모달 플레이어 추가
  src/components/YouTubeAudioPlayer.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
Labels: ✨feat

#83 [design] 페이지에 따른 header, bottom nav 설정
  src/App.tsx
  src/components/MusicAnimation.tsx
  src/layouts/BottomNav.tsx
  src/layouts/Layout.tsx
  src/routes/PrivateRoute.tsx
Labels: 🎨design

#85 [feat] 유저 페이지 음악 플레이어 적용
  src/components/MusicCard.tsx
  src/components/YouTubeAudioPlayer.tsx
  src/pages/userprofile.tsx/UserProfile.tsx
Labels: ✨feat

#88 [design] 정보 수정 페이지 퍼블리싱
  src/App.tsx
  src/layouts/Layout.tsx
  src/pages/editprofile/EditProfile.tsx
Labels: 🎨design

#89 [design] 포스트 페이지 퍼블리싱 및 자잘한 수정
  dev-dist/sw.js
  src/App.tsx
  src/components/EmotionBadge.tsx
  src/components/EmotionFilter.tsx
  src/components/InputField.tsx
  src/constants/limits.ts
  src/pages/Login.tsx
  src/pages/home/Home.tsx
  src/pages/post/Post.tsx
  src/pages/post/components/Comment.tsx
  src/styles/index.css
  src/styles/scrollbar.css
  src/styles/typography.css
Labels: ✨feat, 🎨design

#94 [feat] axios 설정
  src/apis/axios.ts
Labels: ✨feat

#95 [feat] 음악 검색 api 연결 + 무한 스크롤 구현
  src/App.tsx
  src/components/SearchBar.tsx
  src/components/modalSheet/MusicSearchSheet.tsx
  src/hooks/useSpotifyAuth.ts
  src/types/spotify.d.ts
Labels: ✨feat

#103 [feat] spotify 로그인 변경, 음악 로직 수정
  src/components/MusicCard.tsx
  src/components/YouTubeAudioPlayer.tsx
  src/hooks/useSpotifyAuth.ts
  src/pages/chat/components/ChatMusicPlayer.tsx
Labels: ✨feat

#105 [design] 차단 목록 페이지
  src/App.tsx
  src/apis/chat.ts
  src/components/Modal.tsx
  src/hooks/useSpotifyAuth.ts
  src/layouts/Layout.tsx
  src/layouts/header/Header.tsx
  src/pages/Login.tsx
  src/pages/landing/Landing.tsx
  src/pages/userprofile.tsx/BlockList.tsx
  src/pages/userprofile.tsx/UserProfile.tsx
  src/store/modalStore.ts
Labels: 🎨design

#107 [design] 차단 목록 퍼블리싱, Loading 컴포넌트
  package-lock.json
  package.json
  src/apis/blockList.ts
  src/components/Loading.tsx
  src/components/YouTubeAudioPlayer.tsx
  src/hooks/useSpotifyAuth.ts
  src/pages/userprofile.tsx/BlockList.tsx
Labels: 🎨design

#108 [FEAT] 회원가입 구현
  dev-dist/sw.js
  src/apis/email.ts
  src/apis/user.ts
  src/components/CountdownTimer.tsx
  src/components/InputAuthCode.tsx
  src/components/InputField.tsx
  src/constants/email.ts
  src/constants/validation.ts
  src/layouts/Layout.tsx
  src/pages/signup/SignUp.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/signup/components/PasswordConfirmInput.tsx
  src/pages/signup/components/PasswordInput.tsx
  src/styles/tailwind.css
Labels: ✨feat

#111 [feat] 회원가입 모달 추가
  src/apis/email.ts
  src/apis/user.ts
  src/components/Button.tsx
  src/components/InputAuthCode.tsx
  src/components/InputField.tsx
  src/components/Modal.tsx
  src/pages/editprofile/EditProfile.tsx
  src/pages/signup/SignUp.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/signup/components/PasswordConfirmInput.tsx
  src/pages/signup/components/PasswordInput.tsx
  src/store/modalStore.ts
Labels: ✨feat

#113 [feat] refresh token
  src/apis/auth.ts
  src/apis/axios.ts
  src/components/Button.tsx
  src/components/testLogin/TestLoginModal.tsx
  src/pages/home/Home.tsx
  src/store/authStore.ts
  vite.config.ts
Labels: ✨feat

#110 [feat] 채팅 기능 구현 중
  package-lock.json
  package.json
  src/App.tsx
  src/apis/blockList.ts
  src/apis/chat.ts
  src/assets/icons/nav/ChatActive.tsx
  src/assets/icons/nav/HomeActive.tsx
  src/assets/icons/nav/MyPageActive.tsx
  src/assets/icons/nav/mypage-default.svg
  src/components/ChatHistoryCard.tsx
  src/components/EmotionRecordCard.tsx
  src/components/Modal.tsx
  src/components/MusicCard.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/layouts/BottomNav.tsx
  src/layouts/Layout.tsx
  src/layouts/header/HeaderChat.tsx
  src/layouts/header/HeaderWithBack.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  src/pages/userprofile.tsx/BlockList.tsx
  src/styles/tailwind.css
  src/types/chat.d.ts
  vite.config.ts
Labels: ✨feat

#118 feat: 새로운 글 등록 버튼 생성, 우측 하단에 고정
  src/assets/icons/new-post-icon.svg
  src/components/PostButton.tsx
  src/layouts/Layout.tsx
  src/layouts/header/Header.tsx
Labels: ✨feat

#122 [feat] login modal
  src/apis/auth.ts
  src/apis/axios.ts
  src/assets/icons/kakao-icon.svg
  src/components/Modal.tsx
  src/components/testLogin/TestLoginModal.tsx
  src/pages/Login.tsx
  src/pages/post/components/PostPage.tsx
  src/routes/PrivateRoute.tsx
Labels: ✨feat, 🔨refactor

#124 [fix] 노래 검색 오류 수정
  src/App.tsx
  src/components/SearchBar.tsx
  src/components/modalSheet/MusicSearchList.tsx
  src/components/modalSheet/MusicSearchSheet.tsx
  src/layouts/ModalSheetLayout.tsx
  src/pages/blocklist/BlockList.tsx
Labels: 🐛fix

#123 [feat] 글 등록 모달
  src/pages/post/components/Comment.tsx
  src/pages/post/components/PostPage.tsx
Labels: ✨feat

#125 [feat] 날자 형식 추가
  package-lock.json
  package.json
  src/components/modalSheet/CardDetailModal.tsx
  src/pages/userprofile/UserProfile.tsx
  src/utils/formatDate.ts
Labels: ✨feat

#133 [fix] 음악 선택 context -> zustand
  dev-dist/sw.js
  src/components/modalSheet/MusicSearchList.tsx
  src/pages/post/Post.tsx
  src/pages/post/components/PostPage.tsx
  src/pages/post/context/PostMusicContext.tsx
  src/pages/post/context/PostMusicProvider.tsx
  src/store/MusicCardStore.ts
Labels: 🐛fix

#130 fix: 마이/유저페이지 테마곡 없을 경우 수정
  src/components/MusicCard.tsx
Labels: 🐛fix

#134 [feat] 메인 api 연결
  dev-dist/sw.js
  src/apis/emotionRecord.ts
  src/assets/icons/search-icon/clear-icon.svg
  src/components/MainCard.tsx
  src/components/SearchBar.tsx
  src/pages/home/Home.tsx
  src/types/post.d.ts
Labels: ✨feat

#135 [feat] 로딩 컴포넌트 구현
  src/components/Overlay.tsx
  src/components/loading/Loading.tsx
  src/components/loading/LoadingMini.tsx
  src/pages/blocklist/BlockList.tsx
Labels: ✨feat

#138 [feat] 감정 기록 삭제 구현
  src/apis/emotionRecord.ts
  src/components/MoreOptionsSelect.tsx
  src/components/MoreSelectBox.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/layouts/ModalSheetLayout.tsx
  src/pages/userprofile/UserProfile.tsx
Labels: ✨feat

#141 [feat] 마이페이지 무한스크롤 구현
  package-lock.json
  package.json
  src/apis/emotionRecord.ts
  src/pages/userprofile/UserProfile.tsx
Labels: ✨feat

#140 [feat] 마이 페이지 수정 기능 구현
  package-lock.json
  package.json
  src/apis/user.ts
  src/apis/youtube.ts
  src/components/MusicCard.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/MusicSearchList.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  src/pages/editprofile/EditProfile.tsx
  src/pages/signup/components/PasswordConfirmInput.tsx
  src/pages/signup/components/PasswordInput.tsx
  src/pages/userprofile/UserProfile.tsx
  src/store/MusicCardStore.ts
  src/types/post.d.ts
  src/types/user.d.ts
Labels: ✨feat

#142 [fix] modal을 portal로 이동
  src/components/Modal.tsx
Labels: 🐛fix
