Repository prgrms-web-devcourse-final-project/WEB2_3_DFBF_FE, pull requests merged in 2025-03, with the labels that each got.

#143 [feat] 메인 무한 스크롤, 검색 기능 구현했습니다
  src/apis/emotionRecord.ts
  src/pages/home/Home.tsx
Labels: ✨feat

#145 [feat] 유저 페이지 이동
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
Labels: ✨feat

#148 [fix] 카드 상세 모달 위치 수정
  src/pages/home/Home.tsx
Labels: 🐛fix

#152 [fix] TestLoginModal z-index 수정
  src/components/testLogin/TestLoginModal.tsx
Labels: 🐛fix

#153 [feat] 버튼 로딩, 애니메이션, 모달과 시트 오픈 시 스크롤, 모달 overlay 수정, youtube portal로 이동
  src/App.tsx
  src/components/InputAuthCode.tsx
  src/components/InputField.tsx
  src/components/Modal.tsx
  src/components/MoreOptionsSelect.tsx
  src/components/MoreSelectBox.tsx
  src/components/YouTubeAudioPlayer.tsx
  src/components/loading/Complete.tsx
  src/components/loading/ErrorShake.tsx
  src/components/loading/SpinLoading.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/layouts/Layout.tsx
  src/layouts/ModalSheetLayout.tsx
  src/pages/Login.tsx
  src/pages/editprofile/EditProfile.tsx
  src/pages/home/Home.tsx
  src/pages/post/Post.tsx
  src/pages/signup/SignUp.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/userprofile/UserProfile.tsx
  src/styles/index.css
  src/styles/scrollbar.css
  src/styles/tailwind.css
Labels: ✨feat

#155 [refactor] 마이페이지 감정기록 리스트 컴포넌트 분리
  src/pages/userprofile/UserProfile.tsx
  src/pages/userprofile/components/EmotionRecordCardList.tsx
  src/types/post.d.ts
Labels: 🔨refactor

#156 [feat] 게시물 수정 기능 추가
  dev-dist/sw.js
  src/App.tsx
  src/apis/emotionRecord.ts
  src/components/MusicCard.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/MusicSearchList.tsx
  src/pages/post/Post.tsx
  src/pages/post/components/Comment.tsx
  src/pages/userprofile/UserProfile.tsx
Labels: ✨feat

#160 [feat] 채팅 요청, 채팅 요청 취소 구현 + 유저 페이지 이동시 자연스럽게 수정
  src/App.tsx
  src/apis/chat.ts
  src/components/ChatConnectLoadingSheet.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/layouts/Layout.tsx
  src/layouts/ModalSheetLayout.tsx
  src/pages/home/Home.tsx
  src/store/sheetStore.ts
Labels: ✨feat

#161 [feat] 토큰 재발급 로직 추가
  dev-dist/sw.js
  src/apis/auth.ts
  src/apis/axios.ts
Labels: ✨feat

#163 [fix] 토큰 재발급 실패 시 에러 처리
  src/apis/auth.ts
  src/apis/axios.ts
Labels: 🐛fix

#165 [refactor] AnimatedLayout 컴포넌트화
  src/App.tsx
  src/layouts/AnimatedLayout.tsx
Labels: 🔨refactor

#171 [fix] 빌드 에러 삭제
  src/components/MusicCard.tsx
  src/components/testLogin/TestLoginModal.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/userprofile/UserProfile.tsx
Labels: 🐛fix

#172 [feat] 카카오 로그인 구현
  src/App.tsx
  src/apis/auth.ts
  src/components/KaKaoRedirection.tsx
  src/pages/Login.tsx
Labels: ✨feat

#173 [fix] 로그인 포커스 수정, 모달 포커스 추가
  dev-dist/sw.js
  src/components/Button.tsx
  src/components/Modal.tsx
  src/pages/Login.tsx
  src/store/modalStore.ts
Labels: ✨feat, 🐛fix

#174 [feat] 깃허브 액션 추가
  .github/workflows/autoBuild.yml
Labels: 👷chore

#178 [fix] githubAction 수정
  .github/workflows/autoBuild.yml
Labels: 🐛fix

#180 [feat] 회원탈퇴 구현
  src/apis/user.ts
  src/components/KaKaoRedirection.tsx
  src/hooks/useMoreOptions.ts
  src/layouts/Layout.tsx
  src/layouts/header/HeaderWithBack.tsx
Labels: ✨feat, 🔨refactor

#181 [feat] 스포티파이 ID로 비디오 ID 조회 기능 추가
  src/apis/emotionRecord.ts
  src/pages/post/Post.tsx
Labels: ✨feat

#183 [feat] 채팅방 기능 구현, searchYoutube 변경
  src/App.tsx
  src/components/ChatConnectLoadingSheet.tsx
  src/components/MusicCard.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/layouts/header/HeaderChat.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  src/pages/editprofile/EditProfile.tsx
  src/pages/home/components/HomeHeader.tsx
  src/pages/userprofile/UserProfile.tsx
  src/routes/PrivateRoute.tsx
  src/routes/PublicRoute.tsx
  src/routes/index.tsx
  src/store/index.ts
  src/store/sheetStore.ts
  src/styles/index.css
Labels: ✨feat

#188 [refactor] 회원가입 리펙토링
  src/components/InputAuthCode.tsx
  src/components/InputField.tsx
  src/constants/limits.ts
  src/constants/validation.ts
  src/hooks/useEmailCheck.ts
  src/hooks/useEmailVerification.ts
  src/hooks/useEmailVerificationCheck.ts
  src/hooks/useIdAvailability.ts
  src/hooks/useNicknameAvailability.ts
  src/hooks/useResendEmailVerification.ts
  src/hooks/useSignUp.ts
  src/hooks/useValidation.tsx
  src/hooks/useValidationWithButton.ts
  src/pages/signup/SignUp.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/signup/components/PasswordConfirmInput.tsx
  src/pages/signup/components/PasswordInput.tsx
  src/pages/signup/components/SignUpForm.tsx
Labels: 🔨refactor

#194 [chore] env 추가
  .github/workflows/autoBuild.yml
Labels: 👷chore

#192 [refactor] 프로필 수정 페이지
  src/hooks/useValidationWithButton.ts
  src/pages/editprofile/EditProfile.tsx
  src/pages/editprofile/components/CurrentPasswordInput.tsx
  src/pages/editprofile/components/PasswordEditForm.tsx
  src/pages/editprofile/components/ProfileEditForm.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/signup/components/PasswordConfirmInput.tsx
  src/pages/signup/components/PasswordInput.tsx
Labels: 🔨refactor

#195 [chore] 개발 / 배포 api 분리
  src/apis/auth.ts
  src/apis/axios.ts
Labels: 👷chore

#197 [chore] 배포시 필요없는 코드 삭제 및 추가
  src/components/ChatConnectLoadingSheet.tsx
  src/pages/editprofile/components/PasswordEditForm.tsx
  src/pages/editprofile/components/ProfileEditForm.tsx
  src/pages/home/Home.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/userprofile/UserProfile.tsx
  src/pages/userprofile/components/EmotionRecordCardList.tsx
Labels: 👷chore

#200 [feat] 채팅 기능 구현 중, youtube player 수정
  src/apis/axios.ts
  src/apis/chat.ts
  src/components/ChatConnectLoadingSheet.tsx
  src/components/MusicCard.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/layouts/Layout.tsx
  src/layouts/header/HeaderChat.tsx
  src/pages/chat/Chat.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  src/pages/userprofile/UserProfile.tsx
  src/store/scrollStore.ts
  src/types/chat.d.ts
  vite.config.ts
Labels: ✨feat

#198 [feat] error boundary 추가
  dev-dist/sw.js
  package-lock.json
  package.json
  src/components/ErrorBoundary.tsx
  src/components/ErrorFallback.tsx
  src/components/ErrorPage.tsx
  src/layouts/Layout.tsx
  src/pages/NotFound.tsx
Labels: ✨feat

#201 [fix] 채팅 목록 불러오기 수정
  src/components/ChatHistoryCard.tsx
  src/types/chat.d.ts
Labels: 🐛fix

#202 [fix] chatRoom 빌드 수정
  src/pages/chat/ChatRoom.tsx
Labels: 🐛fix

#203 [fix] 프로필 뮤직 삭제 로직 수정
  src/apis/user.ts
  src/components/MusicCard.tsx
  src/pages/editprofile/components/ProfileEditForm.tsx
Labels: 🐛fix

#185 [feat] 회원 가입 폼에서 버튼 로딩 0.1 초 이하면 로딩 컴포넌트 보여주지 않도록 수정
  dev-dist/sw.js
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
Labels: ✨feat

#206 [feat] 마이페이지 로딩 추가
  src/pages/userprofile/UserProfile.tsx
Labels: ✨feat

#208 [chore] 배포서버에서 카카오 로그인시 code 유효성 확인
  src/components/KaKaoRedirection.tsx
Labels: 👷chore

#210 [chore] 카카오 로그인 로직 주석 해제
  src/components/KaKaoRedirection.tsx
Labels: 👷chore

#211 [feat] 프로필 수정 비디오아이디 추가
  src/pages/editprofile/components/ProfileEditForm.tsx
  src/pages/post/Post.tsx
  src/utils/fetchSpotifyVideoId.ts
Labels: ✨feat, 🔨refactor

#212 [feat] createChat api 변경, 유저 차단 시도 시 모달 생성
  src/apis/chat.ts
  src/components/ChatConnectLoadingSheet.tsx
  src/hooks/useMoreOptions.ts
  src/pages/chat/ChatRoom.tsx
  vite.config.ts
Labels: ✨feat

#214 [fix] 게시글 삭제 버그 수정
  src/hooks/useDeleteEmotionRecord.ts
  src/pages/userprofile/UserProfile.tsx
Labels: 🐛fix

#216 [chore] youtube api 등록
  .github/workflows/autoBuild.yml
Labels: 👷chore

#218 [feat] 재전송 횟수 로직 추가
  src/hooks/useResendEmailVerification.ts
  src/pages/signup/components/AuthCodeInput.tsx
Labels: ✨feat

#219 [feat] SSE 연결
  package-lock.json
  package.json
  src/App.tsx
  src/apis/chat.ts
  src/components/ChatConnectLoadingSheet/ChatConnectLoadingSheet.tsx
  src/components/ChatConnectLoadingSheet/ChatRequestButton.tsx
  src/components/ChatConnectLoadingSheet/ChatRequestFailSheet.tsx
  src/components/ChatConnectLoadingSheet/ChatRequestMessage.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/hooks/useSSE.ts
  src/hooks/useYoutube.ts
  src/store/sheetStore.ts
  src/utils/formattedTime.ts
Labels: ✨feat

#222 [fix] 스포티파이 로직 삭제 이슈
  src/App.tsx
Labels: 🐛fix

#223 [design] 테마곡 등록 여부에 따른 텍스트 스타일 수정, 호버 추가
  src/components/EmotionRecordCard.tsx
  src/components/MusicCard.tsx
Labels: 🎨design

#225 [feat] 채팅 기능 구현, chatHistory로 채팅방 입장
  src/components/ChatHistoryCard.tsx
  src/components/modalSheet/CardDetailModal.tsx
  src/hooks/useSSE.ts
  src/pages/chat/ChatRoom.tsx
  src/pages/chat/components/ChatMusicPlayer.tsx
  src/store/chatStore.ts
Labels: ✨feat

#227 [fix] SSE 로직 수정
  src/hooks/useSSE.ts
Labels: 🐛fix

#226 [feat] 이전 대화 기록에서 채팅 요청하기
  src/components/ChatConnectLoadingSheet/ChatRequestButton.tsx
  src/components/ChatConnectLoadingSheet/ChatRequestFailSheet.tsx
  src/components/ChatConnectLoadingSheet/ChatRequestMessage.tsx
  src/components/ChatHistoryCard.tsx
  src/store/chatStore.ts
  src/types/chat.d.ts
Labels: ✨feat

#229 [fix] SSE 재연결 로직 수정
  src/hooks/useSSE.ts
Labels: 🐛fix

#230 [chore] 빌드 오류 수정
  src/hooks/useSSE.ts
Labels: 👷chore

#234 [chore] env 추가
  .github/workflows/autoBuild.yml
Labels: 👷chore

#233 [feat] 채팅 disconnect 하면 상대도 연결 해제, home 이동 시 스크롤 제일 위로, 맥 한글 두번 문제 수정
  src/components/modalSheet/CardDetailModal.tsx
  src/layouts/header/HeaderChat.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/home/Home.tsx
  src/store/chatStore.ts
Labels: ✨feat

#235 [feat] 대화 시작, 종료 시 시스템 메세지 추가
  dev-dist/sw.js
  src/App.tsx
  src/layouts/AnimatedLayout.tsx
  src/layouts/header/HeaderChat.tsx
  src/pages/chat/ChatRoom.tsx
Labels: ✨feat

#236 [fix] 레이아웃 수정, 채팅방 나가기 로직 수정
  src/layouts/AnimatedLayout.tsx
Labels: 🐛fix

#237 [fix] 레이아웃 테스트
  dev-dist/sw.js
  src/components/ChatConnectLoadingSheet/ChatRequestButton.tsx
  src/components/ChatHistoryCard.tsx
  src/layouts/AnimatedLayout.tsx
  src/layouts/header/HeaderChat.tsx
Labels: ✨feat

#239 [refactor] 유저 정보 캐싱
  src/pages/editprofile/components/ProfileEditForm.tsx
  src/pages/userprofile/UserProfile.tsx
Labels: 🔨refactor

#240 fix: 채팅방 닉네임 두번 뜨는 이슈 수정
  src/components/ChatConnectLoadingSheet/ChatRequestButton.tsx
  src/components/ChatHistoryCard.tsx
  src/components/modalSheet/ChatActionButtons.tsx
  src/layouts/header/HeaderChat.tsx
Labels: 🐛fix

#242 [feat] 토큰 만료 체크 자동 발급
  dev-dist/sw.js
  src/App.tsx
  src/hooks/useTokenRefresh.ts
  src/hooks/useUserStatus.ts
Labels: ✨feat

#244 [refactor] 유저페이지 / 마이페이지 리펙토링
  src/App.tsx
  src/apis/emotionRecord.ts
  src/hooks/useDeleteEmotionRecord.ts
  src/pages/editprofile/components/ProfileEditForm.tsx
  src/pages/home/Home.tsx
  src/pages/post/Post.tsx
  src/pages/user/MyPage.tsx
  src/pages/user/UserPage.tsx
  src/pages/user/components/EmotionRecordCardList.tsx
  src/pages/user/components/UserProfile.tsx
  src/pages/userprofile/UserProfile.tsx
Labels: 🔨refactor

#246 [fix] 로그아웃 에러 이슈
  src/apis/axios.ts
  src/hooks/useMoreOptions.ts
Labels: 🐛fix

#248 [refactor] 마이페이지 / 유저페이지 컴포넌트 분리
  src/App.tsx
  src/pages/user/MyPage.tsx
  src/pages/user/UserPage.tsx
  src/pages/user/UserProfile.tsx
  src/pages/user/components/EmotionRecordCardList.tsx
  src/pages/user/components/UserEmotionRecordList/EmotionRecordCard.tsx
  src/pages/user/components/UserEmotionRecordList/EmotionRecordCardList.tsx
  src/pages/user/components/UserEmotionRecordList/MyEmotionRecordList.tsx
  src/pages/user/components/UserEmotionRecordList/OtherEmotionRecordList.tsx
  src/pages/user/components/UserEmotionRecordList/UserEmotionRecordList.tsx
  src/pages/user/components/UserProfileInfo/MyProfileInfo.tsx
  src/pages/user/components/UserProfileInfo/OtherProfileInfo.tsx
  src/pages/user/components/UserProfileInfo/ProfileInfoView.tsx
  src/pages/user/components/UserProfileInfo/UserProfileInfo.tsx
Labels: 🔨refactor

#251 [fix] 유저페이지 0나오는 문제 수정
  src/hooks/user/useInfiniteMyEmotionRecords.ts
  src/hooks/user/useInfiniteOtehrEmotionRecords.ts
  src/hooks/user/useMyProfileInfo.ts
  src/hooks/user/useOtherProfileInfo.ts
  src/hooks/user/useUserProfileLoading.ts
  src/pages/user/UserProfile.tsx
  src/pages/user/components/UserEmotionRecordList/MyEmotionRecordList.tsx
  src/pages/user/components/UserEmotionRecordList/OtherEmotionRecordList.tsx
  src/pages/user/components/UserProfileInfo/MyProfileInfo.tsx
  src/pages/user/components/UserProfileInfo/OtherProfileInfo.tsx
Labels: 🐛fix, 🔨refactor

#254 [refactor] navbar, post 버튼 로직 분리
  src/components/PostButton.tsx
  src/layouts/Layout.tsx
  src/layouts/bottomNav/BottomNav.tsx
  src/layouts/bottomNav/BottomNavWrapper.tsx
Labels: 🔨refactor

#256 [refactor] 헤더 로직 분리
  src/layouts/Layout.tsx
  src/layouts/header/HeaderWrapper.tsx
Labels: 🔨refactor

#257 [refactor] Post 작성/수정 모드 분리 및 submit 로직 정리
  src/components/EmotionFilter.tsx
  src/components/MusicCard.tsx
  src/components/modalSheet/MusicSearchList.tsx
  src/hooks/post/useEditInit.ts
  src/hooks/post/useMusicSelection.ts
  src/hooks/post/usePostCompletion.ts
  src/hooks/post/usePostForm.ts
  src/hooks/post/usePostModals.ts
  src/hooks/post/usePostSubmit.ts
  src/hooks/post/usePostSubmitHandler.ts
  src/pages/home/Home.tsx
  src/pages/post/Post.tsx
  src/pages/post/components/PostCreate.tsx
  src/pages/post/components/PostEdit.tsx
  src/pages/post/components/PostForm.tsx
  src/pages/post/components/PostSubmitButton.tsx
  src/types/post.d.ts
Labels: 🔨refactor

#260 [refactor] 로딩 스피너 버튼 분리
  src/components/ChatConnectLoadingSheet/ChatRequestButton.tsx
  src/components/ChatConnectLoadingSheet/ChatRequestFailSheet.tsx
  src/components/ChatHistoryCard.tsx
  src/components/ErrorPage.tsx
  src/components/InputAuthCode.tsx
  src/components/InputField.tsx
  src/components/Modal.tsx
  src/components/MusicCard.tsx
  src/components/button/Button.tsx
  src/components/button/LoadingSpinnerButton.tsx
  src/components/modalSheet/MusicSearchList.tsx
  src/hooks/useDelayedLoading.ts
  src/hooks/useEmailCheck.ts
  src/hooks/useEmailVerification.ts
  src/hooks/useEmailVerificationCheck.ts
  src/hooks/useIdAvailability.ts
  src/hooks/useValidationWithButton.ts
  src/pages/Login.tsx
  src/pages/blocklist/BlockList.tsx
  src/pages/chat/ChatRoom.tsx
  src/pages/editprofile/components/PasswordEditForm.tsx
  src/pages/editprofile/components/ProfileEditForm.tsx
  src/pages/landing/Landing.tsx
  src/pages/post/components/PostSubmitButton.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/signup/components/SignUpForm.tsx
Labels: 🔨refactor
