Repository prgrms-web-devcourse-final-project/WEB2_3_DFBF_FE, pull requests merged in 2025-07, with the labels that each got.

#303 [refactor] 회원가입 리펙토링
  src/apis/signup.ts
  src/apis/user.ts
  src/components/Main.tsx
  src/components/input/InputField.tsx
  src/components/input/index.ts
  src/constants/index.ts
  src/pages/signup/SignUp.tsx
  src/pages/signup/components/AuthCodeInput.tsx
  src/pages/signup/components/CountdownTimer.tsx
  src/pages/signup/components/EmailGroupSection.tsx
  src/pages/signup/components/EmailInput.tsx
  src/pages/signup/components/IdInput.tsx
  src/pages/signup/components/InputAuthCode.tsx
  src/pages/signup/components/NicknameInput.tsx
  src/pages/signup/components/PasswordConfirmInput.tsx
  src/pages/signup/components/PasswordGroupSection.tsx
  src/pages/signup/components/PasswordInput.tsx
  src/pages/signup/components/SignUpForm.tsx
  src/pages/signup/components/index.ts
Labels: 🔨refactor

#306 [refactor] nav-bar 리펙토링
  src/assets/icons/nav/HomeActive.tsx
  src/assets/icons/nav/index.ts
  src/layouts/Layout.tsx
  src/layouts/bottomNav/BottomNav.tsx
  src/layouts/bottomNav/BottomNavWrapper.tsx
  src/styles/tailwind.css
Labels: 🔨refactor

#309 [REFACTOR] emotionCard props 변경
  src/pages/user/components/UserEmotionRecordList/EmotionRecordCard.tsx
  src/pages/user/components/UserEmotionRecordList/EmotionRecordCardList.tsx
Labels: 🔨refactor

#311 feat: 포스팅 헤더 idempotencykey 추가
  src/apis/emotionRecord.ts
  src/hooks/post/usePostSubmit.ts
Labels: ✨feat

#312 [fix] 모달시트 열릴 때 배경 스크롤 방지 처리 추가
  src/layouts/ModalSheetLayoutTemp.tsx
  src/styles/index.css
Labels: 🐛fix

#313 [feat] scrollLock state 전달하여 스크롤 이동 제어
  src/components/ScrollToTop.tsx
  src/components/modalSheet/BackLink.tsx
  src/components/user/EmotionRecordCardList.tsx
  src/layouts/bottomNav/BottomNav.tsx
Labels: ✨feat
